### ISSUE TITLE
rotate access and error logs

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/nginx-consul#11]
Access and error logs are not being rotated, causing the container filesystem to continually grow. 
- [ ] add log rotate to container
- [ ] implement log rotation for `/var/log/nginx/access.log` and `/var/log/nginx/error.log`

**Comment by ChrisAubuchon** [comment]
What about having all logs go to stdout/stderr and not get logged internally to the container?

**Comment by ryane** [comment]
@siddharthist and I were just talking about this the other day. We would actually be able to collect and (more easily) view the nginx logs for troubleshooting purposes.

**Comment by ChrisAubuchon** [comment]
Should take care of it. https://github.com/CiscoCloud/nginx-consul/pull/12

**Comment by langston-barrett** [comment]
Closed in #12
