### ISSUE TITLE
env NGINX_KV default value is not exported

### ISSUE THREAD

**Issue by avthart** [CiscoCloud/nginx-consul#4]
consul-template can not use the default value (nginx/template/default) because this env var is not exported in the startup script (launch.sh)

Workaround:
You need to the env using "docker run -e NGINX_KV=nginx/template/default"  even if you want to use the default consul key.

**Comment by ChrisAubuchon** [comment]
Thanks! I have added the export in commit https://github.com/CiscoCloud/nginx-consul/commit/e32b23332054228ade438d1a1e1ad7370a2032b9
