### ISSUE TITLE
They're called CONSUL_HTTP_SSL and CONSUL_HTTP_SSL_VERIFY

### ISSUE THREAD

**Issue by eirslett** [CiscoCloud/nginx-consul#8]
and so on... CONSUL_HTTP_***.

https://github.com/hashicorp/consul-template#command-environment

I'm not sure whether this Dockerfile tries to rename them in `launch.sh`, or it's an error/typo/oversight. (In this Dockerfile, it's called CONSUL_SSL and CONSUL_SSL_VERIFY)

**Comment by langston-barrett** [comment]
I don't see anything about these in the Dockerfile, closing.
